pub mod models;
pub mod store;
pub mod handlers;

use std::sync::Arc;
use axum::{
    routing::{get, post, delete},
    Router,
};
use crate::handlers::AppState;

pub fn router() -> Router<Arc<AppState>> {
    Router::new()
        .route(
            "/api/administrativo/acompanhamento-producao",
            get(handlers::get_acompanhamento_producao),
        )
        .route(
            "/api/administrativo/lote-status",
            post(handlers::save_lote_custom_status),
        )
        .route(
            "/api/administrativo/lote-ficha",
            post(handlers::save_ficha_ordem),
        )
        .route(
            "/api/administrativo/lote-status/batch",
            post(handlers::save_batch_lote_custom_status),
        )
        .route(
            "/api/administrativo/lote-status/:number",
            delete(handlers::delete_lote_custom_status),
        )
        .route(
            "/api/administrativo/lote-status/:number/history",
            get(handlers::get_lote_history),
        )
        .route(
            "/api/administrativo/lote-status/:number/terceirizado",
            post(handlers::toggle_terceirizado),
        )
        .route(
            "/api/administrativo/lote-status/:number/previsao",
            post(handlers::save_lote_previsao),
        )
        .route(
            "/api/administrativo/lote-status/:number/timestamps",
            post(handlers::save_lote_timestamps),
        )
        .route(
            "/api/administrativo/lote-status/:number/ocultar-quadro",
            post(handlers::ocultar_quadro_lote),
        )
        .route(
            "/api/administrativo/lote-status/:number/restaurar-quadro",
            post(handlers::restaurar_quadro_lote),
        )
        .route(
            "/api/administrativo/lote-status/:number/etapa-status",
            post(handlers::save_lote_etapa_status),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes",
            get(handlers::get_terceirizados_solicitacoes)
                .post(handlers::create_terceirizados_solicitacao),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes/:id/vincular",
            post(handlers::vincular_terceirizado_solicitacao),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes/:id/desvincular",
            post(handlers::desvincular_terceirizado_solicitacao),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes/:id",
            delete(handlers::delete_terceirizados_solicitacao),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes/:id/aprovar",
            post(handlers::aprovar_terceirizado_solicitacao),
        )
        .route(
            "/api/administrativo/terceirizados/solicitacoes/:id/previsao",
            post(handlers::update_terceirizado_previsao)
                .put(handlers::update_terceirizado_previsao),
        )
        .route(
            "/api/administrativo/terceirizados/produto/:code",
            get(handlers::lookup_produto_terceirizado),
        )
        .route(
            "/api/administrativo/acompanhamento-producao/sheets/config",
            get(handlers::get_sheets_config).post(handlers::save_sheets_config),
        )
        .route(
            "/api/administrativo/acompanhamento-producao/sheets/sync",
            post(handlers::sync_sheets_now),
        )
        .route(
            "/api/administrativo/envase/programacao",
            get(handlers::get_programacao_envase).post(handlers::save_programacao_envase),
        )
        .route(
            "/api/administrativo/envase/programacao/:id",
            delete(handlers::delete_programacao_envase),
        )
        .route(
            "/api/administrativo/envase/programacao/lote/:lote_number",
            delete(handlers::delete_programacao_envase_by_lote),
        )
        .route(
            "/api/administrativo/envase/programacao/reorder",
            post(handlers::reorder_programacao_envase),
        )
        .route(
            "/api/administrativo/rotulagem/programacao",
            get(handlers::get_programacao_rotulagem).post(handlers::save_programacao_rotulagem),
        )
        .route(
            "/api/administrativo/rotulagem/programacao/:id",
            delete(handlers::delete_programacao_rotulagem),
        )
        .route(
            "/api/administrativo/rotulagem/programacao/lote/:lote_number",
            delete(handlers::delete_programacao_rotulagem_by_lote),
        )
        .route(
            "/api/administrativo/rotulagem/programacao/reorder",
            post(handlers::reorder_programacao_rotulagem),
        )
}
