import type { LabelTemplate } from './types';

export const DEFAULT_LABEL_TEMPLATES: LabelTemplate[] = [
  {
    id: 'template_materia_prima',
    name: 'Identificação de Matéria-Prima',
    description: 'Etiqueta padrão para identificação e recebimento de insumos químicos e matérias-primas no estoque.',
    category: 'estoque',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      // Outer border
      {
        id: 'border_1',
        type: 'box',
        x_mm: 1,
        y_mm: 1,
        width_mm: 98,
        height_mm: 48,
        zIndex: 1,
        props: {
          borderWidth: 0.6,
          borderColor: '#18181b',
          backgroundColor: 'transparent',
          borderRadius: 2,
        },
      },
      // Header brand
      {
        id: 'brand_title',
        type: 'text',
        x_mm: 3.5,
        y_mm: 2.8,
        width_mm: 55,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'NÁTUM BIO COSMÉTICOS',
          fontSize: 9,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
        },
      },
      // Header Badge
      {
        id: 'badge_mp',
        type: 'badge',
        x_mm: 62,
        y_mm: 2.5,
        width_mm: 34,
        height_mm: 5.5,
        zIndex: 2,
        props: {
          text: 'MATÉRIA-PRIMA',
          variant: 'black',
          fontSize: 8,
          fontWeight: 'bold',
          uppercase: true,
          borderRadius: 1,
        },
      },
      // Divider
      {
        id: 'line_1',
        type: 'line',
        x_mm: 3.5,
        y_mm: 8.5,
        width_mm: 93,
        height_mm: 0.5,
        zIndex: 2,
        props: {
          orientation: 'horizontal',
          strokeWidth: 0.4,
          strokeColor: '#18181b',
          strokeStyle: 'solid',
        },
      },
      // Product Name
      {
        id: 'txt_name_label',
        type: 'text',
        x_mm: 3.5,
        y_mm: 9.8,
        width_mm: 65,
        height_mm: 3.5,
        zIndex: 2,
        props: {
          text: 'DESCRIÇÃO DO INSUMO:',
          fontSize: 6,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#71717a',
        },
      },
      {
        id: 'txt_product_name',
        type: 'text',
        x_mm: 3.5,
        y_mm: 13.2,
        width_mm: 65,
        height_mm: 9,
        zIndex: 2,
        props: {
          text: 'ÓLEO DE ARGAN PURO ORGÂNICO',
          fontSize: 11,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
          multiline: true,
        },
      },
      // Code & Batch details
      {
        id: 'txt_code',
        type: 'text',
        x_mm: 3.5,
        y_mm: 23,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'CÓDIGO: MP-00412',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_lote',
        type: 'text',
        x_mm: 36,
        y_mm: 23,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'LOTE: 2026-0815',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      // Dates (Fabricação & Validade)
      {
        id: 'txt_fab',
        type: 'text',
        x_mm: 3.5,
        y_mm: 29,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'FAB: 10/08/2026',
          fontSize: 8,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_val',
        type: 'text',
        x_mm: 36,
        y_mm: 29,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'VAL: 10/08/2028',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      // Weight / Qty
      {
        id: 'txt_peso',
        type: 'text',
        x_mm: 3.5,
        y_mm: 35,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'PESO LÍQ: 25.000 KG',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_fornecedor',
        type: 'text',
        x_mm: 36,
        y_mm: 35,
        width_mm: 32,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'FORN: QUÍMICA BRASIL',
          fontSize: 7.5,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      // Barcode / QR Code on right side
      {
        id: 'qr_code_1',
        type: 'qrcode',
        x_mm: 71,
        y_mm: 12,
        width_mm: 25,
        height_mm: 25,
        zIndex: 2,
        props: {
          value: 'MP-00412|2026-0815|VAL:2028-08',
          errorCorrectionLevel: 'M',
        },
      },
      // Footer text
      {
        id: 'txt_footer',
        type: 'text',
        x_mm: 3.5,
        y_mm: 42.5,
        width_mm: 93,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'CONTROLE INTERNO DE QUALIDADE · ARMAZENAR EM LOCAL FRESCO E SECO',
          fontSize: 5.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
        },
      },
    ],
  },
  {
    id: 'template_embalagem',
    name: 'Identificação de Embalagens & Frascos',
    description: 'Etiqueta para caixas de frascos, tampas, válvulas e rótulos no estoque.',
    category: 'estoque',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      {
        id: 'border_1',
        type: 'box',
        x_mm: 1,
        y_mm: 1,
        width_mm: 98,
        height_mm: 48,
        zIndex: 1,
        props: {
          borderWidth: 0.6,
          borderColor: '#18181b',
          backgroundColor: 'transparent',
          borderRadius: 2,
        },
      },
      {
        id: 'brand_title',
        type: 'text',
        x_mm: 3.5,
        y_mm: 2.8,
        width_mm: 55,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'NÁTUM BIO COSMÉTICOS',
          fontSize: 9,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
        },
      },
      {
        id: 'badge_emb',
        type: 'badge',
        x_mm: 62,
        y_mm: 2.5,
        width_mm: 34,
        height_mm: 5.5,
        zIndex: 2,
        props: {
          text: 'EMBALAGEM',
          variant: 'black',
          fontSize: 8,
          fontWeight: 'bold',
          uppercase: true,
          borderRadius: 1,
        },
      },
      {
        id: 'line_1',
        type: 'line',
        x_mm: 3.5,
        y_mm: 8.5,
        width_mm: 93,
        height_mm: 0.5,
        zIndex: 2,
        props: {
          orientation: 'horizontal',
          strokeWidth: 0.4,
          strokeColor: '#18181b',
          strokeStyle: 'solid',
        },
      },
      {
        id: 'txt_emb_name',
        type: 'text',
        x_mm: 3.5,
        y_mm: 10.5,
        width_mm: 93,
        height_mm: 8,
        zIndex: 2,
        props: {
          text: 'FRASCO PET 250ML CILÍNDRICO ÂMBAR R24',
          fontSize: 10.5,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
        },
      },
      {
        id: 'txt_emb_code',
        type: 'text',
        x_mm: 3.5,
        y_mm: 19.5,
        width_mm: 45,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'CÓDIGO: EMB-00128',
          fontSize: 8.5,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_emb_qtd',
        type: 'text',
        x_mm: 50,
        y_mm: 19.5,
        width_mm: 46,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'QTD CAIXA: 200 UN',
          fontSize: 9,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'right',
          color: '#18181b',
        },
      },
      // Barcode
      {
        id: 'barcode_emb',
        type: 'barcode',
        x_mm: 10,
        y_mm: 25.5,
        width_mm: 80,
        height_mm: 15,
        zIndex: 2,
        props: {
          value: 'EMB00128',
          format: 'code128',
          showText: true,
          fontSize: 8,
        },
      },
      {
        id: 'txt_resp',
        type: 'text',
        x_mm: 3.5,
        y_mm: 42.5,
        width_mm: 93,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'CONFERIDO POR: ___________________  DATA: ___/___/______',
          fontSize: 6.5,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
        },
      },
    ],
  },
  {
    id: 'template_produto_acabado',
    name: 'Produto Acabado / Amostra',
    description: 'Etiqueta para produtos cosméticos acabados, lotes piloto ou amostras de retenção.',
    category: 'producao',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      {
        id: 'border_1',
        type: 'box',
        x_mm: 1,
        y_mm: 1,
        width_mm: 98,
        height_mm: 48,
        zIndex: 1,
        props: {
          borderWidth: 0.6,
          borderColor: '#18181b',
          backgroundColor: 'transparent',
          borderRadius: 2,
        },
      },
      {
        id: 'brand_title',
        type: 'text',
        x_mm: 3.5,
        y_mm: 2.8,
        width_mm: 60,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'NÁTUM BIO COSMÉTICOS',
          fontSize: 9,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
        },
      },
      {
        id: 'txt_conteudo',
        type: 'text',
        x_mm: 65,
        y_mm: 2.8,
        width_mm: 31,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'VOL. LÍQ: 500 ML',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'right',
          color: '#18181b',
        },
      },
      {
        id: 'line_1',
        type: 'line',
        x_mm: 3.5,
        y_mm: 8.5,
        width_mm: 93,
        height_mm: 0.5,
        zIndex: 2,
        props: {
          orientation: 'horizontal',
          strokeWidth: 0.4,
          strokeColor: '#18181b',
          strokeStyle: 'solid',
        },
      },
      {
        id: 'txt_prod_title',
        type: 'text',
        x_mm: 3.5,
        y_mm: 10,
        width_mm: 93,
        height_mm: 8,
        zIndex: 2,
        props: {
          text: 'MÁSCARA HIDRATANTE BANHO DE VERNIZ',
          fontSize: 11,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
          uppercase: true,
        },
      },
      {
        id: 'txt_lote_fab',
        type: 'text',
        x_mm: 3.5,
        y_mm: 19.5,
        width_mm: 30,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'LOTE: 2026-081',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_fab_date',
        type: 'text',
        x_mm: 35,
        y_mm: 19.5,
        width_mm: 30,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'FAB: 13/08/2026',
          fontSize: 8,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
        },
      },
      {
        id: 'txt_val_date',
        type: 'text',
        x_mm: 66,
        y_mm: 19.5,
        width_mm: 30,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'VAL: 13/08/2028',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'right',
          color: '#18181b',
        },
      },
      // Barcode
      {
        id: 'barcode_ean',
        type: 'barcode',
        x_mm: 12,
        y_mm: 25.5,
        width_mm: 76,
        height_mm: 16,
        zIndex: 2,
        props: {
          value: '7898912345678',
          format: 'ean13',
          showText: true,
          fontSize: 8.5,
        },
      },
      {
        id: 'txt_obs',
        type: 'text',
        x_mm: 3.5,
        y_mm: 43.5,
        width_mm: 93,
        height_mm: 4,
        zIndex: 2,
        props: {
          text: 'INDÚSTRIA BRASILEIRA · USO PROFISSIONAL',
          fontSize: 6,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#71717a',
        },
      },
    ],
  },
  {
    id: 'template_controle_qualidade',
    name: 'Status de Controle de Qualidade',
    description: 'Etiqueta de inspeção laboratorial (Aprovado / Quarentena / Reprovado).',
    category: 'qualidade',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      {
        id: 'border_1',
        type: 'box',
        x_mm: 1,
        y_mm: 1,
        width_mm: 98,
        height_mm: 48,
        zIndex: 1,
        props: {
          borderWidth: 0.8,
          borderColor: '#18181b',
          backgroundColor: 'transparent',
          borderRadius: 2,
        },
      },
      {
        id: 'badge_status',
        type: 'badge',
        x_mm: 3.5,
        y_mm: 3,
        width_mm: 93,
        height_mm: 11,
        zIndex: 2,
        props: {
          text: 'LIBERADO / APROVADO CQ',
          variant: 'black',
          fontSize: 14,
          fontWeight: '800',
          uppercase: true,
          borderRadius: 2,
        },
      },
      {
        id: 'txt_prod_desc',
        type: 'text',
        x_mm: 3.5,
        y_mm: 16,
        width_mm: 93,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'PRODUTO / LOTE: SHAMPOO NUTRITIVO 1L - LOTE 2026-092',
          fontSize: 8.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_analista',
        type: 'text',
        x_mm: 3.5,
        y_mm: 22,
        width_mm: 45,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'ANALISTA: CONTROLE CQ',
          fontSize: 8,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_data_lib',
        type: 'text',
        x_mm: 50,
        y_mm: 22,
        width_mm: 46,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'DATA LIBERAÇÃO: 13/08/2026',
          fontSize: 8,
          fontWeight: '600',
          fontFamily: 'Inter',
          textAlign: 'right',
          color: '#18181b',
        },
      },
      {
        id: 'txt_ph',
        type: 'text',
        x_mm: 3.5,
        y_mm: 28,
        width_mm: 30,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'pH: 4.5 - 5.5 (OK)',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'txt_visc',
        type: 'text',
        x_mm: 35,
        y_mm: 28,
        width_mm: 30,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'VISC: 8.500 cPs',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'center',
          color: '#18181b',
        },
      },
      {
        id: 'txt_micro',
        type: 'text',
        x_mm: 66,
        y_mm: 28,
        width_mm: 30,
        height_mm: 5,
        zIndex: 2,
        props: {
          text: 'MICRO: NEGATIVO',
          fontSize: 8,
          fontWeight: 'bold',
          fontFamily: 'JetBrains Mono',
          textAlign: 'right',
          color: '#18181b',
        },
      },
      {
        id: 'line_cq',
        type: 'line',
        x_mm: 3.5,
        y_mm: 34.5,
        width_mm: 93,
        height_mm: 0.5,
        zIndex: 2,
        props: {
          orientation: 'horizontal',
          strokeWidth: 0.4,
          strokeColor: '#18181b',
          strokeStyle: 'solid',
        },
      },
      {
        id: 'txt_assinatura',
        type: 'text',
        x_mm: 3.5,
        y_mm: 38,
        width_mm: 93,
        height_mm: 8,
        zIndex: 2,
        props: {
          text: 'ASSINATURA RESPONSÁVEL TÉCNICO: ____________________________',
          fontSize: 7.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
        },
      },
    ],
  },
  {
    id: 'template_caixa_volume',
    name: 'Identificação de Caixa / Volume',
    description: 'Etiqueta de expedição com numeração sequencial de volume (ex: Vol 01/10).',
    category: 'expedicao',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      {
        id: 'border_1',
        type: 'box',
        x_mm: 1,
        y_mm: 1,
        width_mm: 98,
        height_mm: 48,
        zIndex: 1,
        props: {
          borderWidth: 0.8,
          borderColor: '#18181b',
          backgroundColor: 'transparent',
          borderRadius: 2,
        },
      },
      {
        id: 'txt_dest',
        type: 'text',
        x_mm: 3.5,
        y_mm: 3,
        width_mm: 55,
        height_mm: 4,
        zIndex: 2,
        props: {
          text: 'DESTINATÁRIO / CLIENTE:',
          fontSize: 6.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#71717a',
        },
      },
      {
        id: 'txt_cliente',
        type: 'text',
        x_mm: 3.5,
        y_mm: 7,
        width_mm: 60,
        height_mm: 8,
        zIndex: 2,
        props: {
          text: 'DISTRIBUIDORA COSMÉTICA LTDA',
          fontSize: 10,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
          uppercase: true,
        },
      },
      {
        id: 'badge_volume',
        type: 'badge',
        x_mm: 66,
        y_mm: 3,
        width_mm: 30,
        height_mm: 12,
        zIndex: 2,
        props: {
          text: 'VOL. 01/10',
          variant: 'black',
          fontSize: 12,
          fontWeight: '800',
          uppercase: true,
          borderRadius: 2,
        },
      },
      {
        id: 'line_box',
        type: 'line',
        x_mm: 3.5,
        y_mm: 16.5,
        width_mm: 93,
        height_mm: 0.5,
        zIndex: 2,
        props: {
          orientation: 'horizontal',
          strokeWidth: 0.4,
          strokeColor: '#18181b',
          strokeStyle: 'solid',
        },
      },
      {
        id: 'txt_conteudo_label',
        type: 'text',
        x_mm: 3.5,
        y_mm: 18,
        width_mm: 93,
        height_mm: 4,
        zIndex: 2,
        props: {
          text: 'CONTEÚDO: 24x MÁSCARA CAPILAR 500G',
          fontSize: 8.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'left',
          color: '#18181b',
        },
      },
      {
        id: 'barcode_vol',
        type: 'barcode',
        x_mm: 10,
        y_mm: 24,
        width_mm: 80,
        height_mm: 16,
        zIndex: 2,
        props: {
          value: 'PED-98231-VOL01',
          format: 'code128',
          showText: true,
          fontSize: 8,
        },
      },
      {
        id: 'txt_footer_box',
        type: 'text',
        x_mm: 3.5,
        y_mm: 42.5,
        width_mm: 93,
        height_mm: 4.5,
        zIndex: 2,
        props: {
          text: 'PESO BRUTO: 12.8 KG · MANUSEIE COM CUIDADO (FRÁGIL)',
          fontSize: 6.5,
          fontWeight: 'bold',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
        },
      },
    ],
  },
  {
    id: 'template_branco',
    name: 'Etiqueta em Branco (100x50mm)',
    description: 'Comece a partir de uma etiqueta 100x50mm vazia e adicione seus elementos livremente.',
    category: 'custom',
    width_mm: 100,
    height_mm: 50,
    orientation: 'landscape',
    is_default: true,
    elements_json: [
      {
        id: 'brand_title',
        type: 'text',
        x_mm: 5,
        y_mm: 5,
        width_mm: 90,
        height_mm: 8,
        zIndex: 1,
        props: {
          text: 'TÍTULO DA ETIQUETA',
          fontSize: 12,
          fontWeight: '800',
          fontFamily: 'Inter',
          textAlign: 'center',
          color: '#18181b',
          uppercase: true,
        },
      },
    ],
  },
];
